### ISSUE TITLE
Compilation errors for 0.3.3.0

### ISSUE THREAD

**Issue by alexanderkjeldaas** [basvandijk/monad-control#21]
I am getting compilation errors

ghc  --version
The Glorious Glasgow Haskell Compilation System, version 7.8.3

Preprocessing library monad-control-0.3.3.0...
[1 of 1] Compiling Control.Monad.Trans.Control ( Control/Monad/Trans/Control.hs, dist/dist-sandbox-231cbf33/build/Control/Monad/Trans/Control.o )

Control/Monad/Trans/Control.hs:343:10:
    No instance for (MonadBase Identity Identity)
      arising from the superclasses of an instance declaration
    In the instance declaration for
      ‘MonadBaseControl Identity Identity’

Control/Monad/Trans/Control.hs:431:10:
    Could not deduce (MonadBase b (IdentityT m))
      arising from the superclasses of an instance declaration
    from the context (MonadBaseControl b m)
      bound by the instance declaration
      at Control/Monad/Trans/Control.hs:431:10-72
    In the instance declaration for ‘MonadBaseControl b (IdentityT m)’

Control/Monad/Trans/Control.hs:432:10:
    Could not deduce (MonadBase b (MaybeT m))
      arising from the superclasses of an instance declaration
    from the context (MonadBaseControl b m)
      bound by the instance declaration
      at Control/Monad/Trans/Control.hs:432:10-69
    In the instance declaration for ‘MonadBaseControl b (MaybeT m)’

Control/Monad/Trans/Control.hs:433:10:
    Could not deduce (MonadBase b (ListT m))
      arising from the superclasses of an instance declaration
    from the context (MonadBaseControl b m)
      bound by the instance declaration
      at Control/Monad/Trans/Control.hs:433:10-68
    In the instance declaration for ‘MonadBaseControl b (ListT m)’

Control/Monad/Trans/Control.hs:434:10:
    Could not deduce (MonadBase b (ReaderT r m))
      arising from the superclasses of an instance declaration
    from the context (MonadBaseControl b m)
      bound by the instance declaration
      at Control/Monad/Trans/Control.hs:434:10-72
    In the instance declaration for ‘MonadBaseControl b (ReaderT r m)’

Control/Monad/Trans/Control.hs:435:10:
    Could not deduce (MonadBase b (Strict.StateT s m))
      arising from the superclasses of an instance declaration
    from the context (MonadBaseControl b m)
      bound by the instance declaration
      at Control/Monad/Trans/Control.hs:435:10-78
    In the instance declaration for
      ‘MonadBaseControl b (Strict.StateT s m)’

Control/Monad/Trans/Control.hs:436:10:
    Could not deduce (MonadBase b (StateT s m))
      arising from the superclasses of an instance declaration
    from the context (MonadBaseControl b m)
      bound by the instance declaration
      at Control/Monad/Trans/Control.hs:436:10-78
    In the instance declaration for ‘MonadBaseControl b (StateT s m)’

Control/Monad/Trans/Control.hs:439:10:
    Could not deduce (MonadBase b (ExceptT e m))
      arising from the superclasses of an instance declaration
    from the context (MonadBaseControl b m)
      bound by the instance declaration
      at Control/Monad/Trans/Control.hs:439:10-72
    In the instance declaration for ‘MonadBaseControl b (ExceptT e m)’

Control/Monad/Trans/Control.hs:442:10:
    Could not deduce (MonadBase b (ErrorT e m))
      arising from the superclasses of an instance declaration
    from the context (Error e, MonadBaseControl b m)
      bound by the instance declaration
      at Control/Monad/Trans/Control.hs:442:10-84
    In the instance declaration for ‘MonadBaseControl b (ErrorT e m)’

Control/Monad/Trans/Control.hs:443:10:
    Could not deduce (MonadBase b (Strict.WriterT w m))
      arising from the superclasses of an instance declaration
    from the context (Monoid w, MonadBaseControl b m)
      bound by the instance declaration
      at Control/Monad/Trans/Control.hs:443:10-85
    In the instance declaration for
      ‘MonadBaseControl b (Strict.WriterT w m)’

Control/Monad/Trans/Control.hs:444:10:
    Could not deduce (MonadBase b (WriterT w m))
      arising from the superclasses of an instance declaration
    from the context (Monoid w, MonadBaseControl b m)
      bound by the instance declaration
      at Control/Monad/Trans/Control.hs:444:10-85
    In the instance declaration for ‘MonadBaseControl b (WriterT w m)’

Control/Monad/Trans/Control.hs:445:10:
    Could not deduce (MonadBase b (Strict.RWST r w s m))
      arising from the superclasses of an instance declaration
    from the context (Monoid w, MonadBaseControl b m)
      bound by the instance declaration
      at Control/Monad/Trans/Control.hs:445:10-86
    In the instance declaration for
      ‘MonadBaseControl b (Strict.RWST r w s m)’

Control/Monad/Trans/Control.hs:446:10:
    Could not deduce (MonadBase b (RWST r w s m))
      arising from the superclasses of an instance declaration
    from the context (Monoid w, MonadBaseControl b m)
      bound by the instance declaration
      at Control/Monad/Trans/Control.hs:446:10-86
    In the instance declaration for ‘MonadBaseControl b (RWST r w s m)’

**Comment by alexanderkjeldaas** [comment]
I have lost this environment, sorry.

**Comment by basvandijk** [comment]
No problem. Let's reopen it when the problem reoccurs.
