### ISSUE TITLE
Add MonadIO instance for MonadBaseControl IO

### ISSUE THREAD

**Issue by winterland1989** [basvandijk/monad-control#37]
Is it possible to have `MonadIO m` 's instance for `MonadBaseControl IO m`?  I'm not sure, but i think doing so can save lots of instance declarations maybe.

**Comment by basvandijk** [comment]
I'm not sure what you mean. Do you mean that having the following instance would be convenient?

```haskell
instance (MonadIO m) => MonadBase IO m where liftBase = liftIO
```

Maybe it's wise to add this "catch-all" instance to `transformers-base`. @mvv would this have any negative consequences?

**Comment by mvv** [comment]
It would conflict with any other instance of `MonadBase` because of the FD `m -> IO`.

**Comment by winterland1989** [comment]
That makes sense!

**Comment by winterland1989** [comment]
That makes sense!
