### ISSUE TITLE
Documentation nitpick: laws require impredicativity

### ISSUE THREAD

**Issue by Lysxia** [basvandijk/monad-control#44]
It's a small thing that came up when trying to write a testable version of class laws.

For example, the first law that is mentioned for `MonadTransControl` is:

    liftWith . const . return = return

Here `const` must have type `m a -> Run t -> m a`, in particular, `Run t` is a rank-1 type; for the left hand side to typecheck, we need impredicative types, which GHC doesn't support.

On the one hand, this is only a limitation of the type system, and the equations still make sense semantically. On the other hand, snippets in the documentation that won't typecheck can be confusing if you actually try to compile them.

I don't have a good solution for now. Lack of impredicativity is usually addressed by being more pointful, but arguably these laws look nicer in pointfree style.

One alternative that typechecks is

    liftWith (\_ -> return a) = return a  -- for all a

**Comment by Lysxia** [comment]
Actually, that last alternative formulation would have the side effect of making the type of both sides in the first law have the same shape as the type in the second law.

    liftWith (\_ -> return a) = return a      :: t m a
    liftWith (\_ -> m >>= k) = liftWith (\_ -> m) >>= \a -> liftWith (\_ -> k a)     :: t m b

And the transformation doesn't look so bad for the third law (which implies the first two, and is somewhat more canonical)

    liftWith (\_ -> f) = lift f  -- instead of   liftWith (const f) = lift f

**Comment by basvandijk** [comment]
Thanks for bringing this up! I agree the point-full laws look quite nice. Care to submit a PR?
